blog/urls.py
from blog import views
from django.conf.urls import url
from django.views.decorators.cache import cache_page


app_name = 'blog'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^about/', views.about),
    url(r'^signup/', views.signup),
    url(r'^logout/', views.logout_view),
    url(r'^contact/', views.contact, name='contact'),
    url(r'^full-width/', views.FullView.as_view(), name='blog'),
    # url(r'^article/(?P<pk>[0-9]+)/$', views.detail, name='detail'),
    url(r'^article/(?P<pk>[0-9]+)/$', cache_page(60 * 15)(views.PostDetailView.as_view()), name='detail'),
    # url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.archives, name='archives'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.ArchivesView.as_view(), name='archives'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.CategoryView.as_view(), name='category'),
    url(r'^tag/(?P<pk>[0-9]+)/$', views.TagView.as_view(), name='tag'),
]

comments/urls.py
from django.conf.urls import url
from . import views


app_name = 'comments'
urlpatterns = [
    url(r'^comment/article/(?P<article_pk>[0-9]+)/$', views.article_comment, name='article_comment'),
]

xlc_blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from blog.feeds import ArticleRssFeed

urlpatterns = [
    url(r'^admin/', admin.site.urls,name="admin"),
    url(r'^', include('blog.urls')),
    url(r'^', include('comments.urls')),
    url(r'^all/rss', ArticleRssFeed(), name='rss'),
    url(r'search/', include('haystack.urls'))
]

comments/models.py
from django.db import models

# Create your models here.


class Comment(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=255)
    url = models.URLField(blank=True)
    created_date = models.DateTimeField(auto_now_add=True)
    article = models.ForeignKey('blog.Article')
    text = models.TextField()

    def __str__(self):
        return self.text[:20]

blog/forms.py
from django import forms
from django.conf import settings
from django.contrib.auth import get_user_model
from django.contrib.auth import authenticate
from django.utils.translation import ugettext, ugettext_lazy as _
from .models import Contact
import re


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['name', 'email', 'subject', 'message']
        widgets = {
            'name': forms.TextInput(attrs={
                'type': 'name',
                'placeholder': 'Name',
                }),
            'email': forms.TextInput(attrs={
                'type': 'name',
                'placeholder': 'Email'
            }),
            'subject': forms.TextInput(attrs={
                'type': 'subject',
                'placeholder': 'Subject'
            }),
            'message': forms.Textarea(attrs={
                'type': 'message',
                'placeholder': 'Message',
                'row': 7,
            }),
        }


def lowercase_email(email):
    """
        Normalize the address by lowercasing the domain part of the email
        address.
        """
    email = email or ''
    try:
        email_name, domain_part = email.strip().rsplit('@', 1)
    except ValueError:
        pass
    else:
        email = '@'.join([email_name.lower(), domain_part.lower()])
    return email


class SignupForm(forms.ModelForm):
    username = forms.CharField(
        label='用户名', required=True,
        error_messages={'required': '请填写你的用户名', 'max_length': '最多只能输入15个字符', 'min_length': '至少输入3个字符'}, max_length=15,
        min_length=3, widget=forms.TextInput(attrs={'placeholder': '3~15位字母/数字/汉字'}))
    email = forms.EmailField(error_messages={'required': '请填写你的email', 'invalid': 'email格式不正确'},
                             label='邮箱', required=True,
                             widget=forms.EmailInput(attrs={'placeholder': '填写正确的email以便激活你的账户'}))
    password = forms.CharField(
        error_messages={'required': '请输入密码', 'max_length': '最多只能输入20个字符', 'min_length': '至少输入6个字符'},
        label='密码', required=True, max_length=20, widget=forms.PasswordInput(attrs={'placeholder': '长度在6~20个字符以内'}))
    confirm_password = forms.CharField(
        error_messages={'required': '请输入密码', 'max_length': '最多只能输入20个字符', 'min_length': '至少输入6个字符'},
        label='确认密码', required=True, max_length=20, min_length=6,
        widget=forms.PasswordInput(attrs={'placeholder': '长度在6~20个字符以内'}))

    class Meta:
        model = get_user_model()
        fields = ("username", "email", "password",)

    def clean_email(self):
        UserModel = get_user_model()
        email = self.cleaned_data["email"]
        lower_email = lowercase_email(email)
        try:
            UserModel._default_manager.get(email=lower_email)
        except UserModel.DoesNotExist:
            return lower_email
        raise forms.ValidationError("有人已经注册了这个email地址")

    def clean_confirm_password(self):
        # cleaned_data=super(SignupForm,self).clean()
        password = self.cleaned_data.get("password", False)
        confirm_password = self.cleaned_data["confirm_password"]
        if not (password == confirm_password):
            raise forms.ValidationError("确认密码和密码不一致")
        return confirm_password

    def clean_username(self):
        UserModel = get_user_model()
        username = self.cleaned_data["username"]
        # 过滤用户名敏感词的注册用户
        n = re.sub('[^\u4e00-\u9fa5a-zA-Z]', '', username)

        mgc = ['admin', 'fanhuaxiu', '繁花社长']

        if n in mgc:
            raise forms.ValidationError("这么好的名字当然被人提前预定啦，换一个试试^-^")

        try:
            UserModel._default_manager.get(username=username)

        except UserModel.DoesNotExist:
            return username
        raise forms.ValidationError("有人已经注册了这个用户名")


blog/views.py
from django.shortcuts import render, redirect, get_object_or_404

from django.contrib.auth import authenticate, login as auth_login, logout
from blog.forms import SignupForm
from django.contrib.auth import get_user_model
from blog.models import Article, Category, Tag
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
import markdown
from comments.forms import CommentForm
from blog.forms import ContactForm
from django.utils.html import strip_tags
from markdown.extensions.toc import TocExtension
from django.utils.text import slugify
from django.db.models import Q
from django.core.mail import send_mail
from .tasks import celery_send_email
# Create your views here.

# def home(request):
#     article_list = Article.objects.all().order_by('-created_date')
#
#     return render(request, 'blog/index.html', locals())


class IndexView(ListView):
    model = Article
    template_name = 'blog/index.html'
    context_object_name = 'article_list'
    paginate_by = 4

    # def get_queryset(self):
    #     article_list = Article.objects.filter(is_show=True)
    #     for article in article_list:
    #         article.content = strip_tags(markdown.markdown(article.content,))[:54]
    #     return article_list

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        paginator = context.get('paginator')
        page = context.get('page_obj')
        is_paginated = context.get('is_paginated')

        pagination_data = self.pagination_data(paginator, page, is_paginated)
        context.update(pagination_data)

        return context

    def pagination_data(self, paginator, page, is_paginated):
        if not is_paginated:
            return {}
        left = []
        right = []
        left_has_more = []
        right_has_more = []
        first = False
        last = False
        page_number = page.number
        total_pages = paginator.num_pages
        page_range = paginator.page_range

        if page_number == 1:
            right = page_range[page_number:page_number + 2]

            if right[-1] < total_pages -1:
                right_has_more = True
            if right[-1] < total_pages:
                last = True

        elif page_number == total_pages:
            left = page_range[(page_number - 3) if (page_number -3 > 0) else 0:page_number - 1]

            if left[0] > 2:
                left_has_more = True

            if left[0] > 1:
                first = True
        else:
            left = page_range[(page_number - 3) if (page_number -3 > 0) else 0:page_number - 1]
            right = page_range[page_number:page_range + 2]

            if right[-1] < total_pages -1:
                right_has_more = True
            if right[-1] < total_pages:
                last = True

            if left[0] > 2:
                left_has_more = True

            if left[0] > 1:
                first = True

        data = {
            'left': left,
            'right': right,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more,
            'first': first,
            'last': last,
        }

        return data


'''
def detail(request, pk):
    article = get_object_or_404(Article, pk=pk)
    article.increase_views()
    article.content = markdown.markdown(article.content,
                                     extensions=[
                                         'markdown.extensions.extra',
                                         'markdown.extensions.codehilite',
                                         'markdown.extensions.toc',
                                     ])
    form = CommentForm()
    comment_list = article.comment_set.all()
    context = {
        'article': article,
        'form': form,
        'comment_list': comment_list
    }
    return render(request, 'blog/detail.html', context=context)
'''


class PostDetailView(DetailView):
    model = Article
    template_name = 'blog/detail.html'
    context_object_name = 'article'

    def get(self, request, *args, **kwargs):
        response = super(PostDetailView, self).get(request, *args, **kwargs)
        self.object.increase_views()
        return response

    def get_object(self, queryset=None):
        article = super(PostDetailView, self).get_object(queryset=None)
        md = markdown.Markdown(extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            TocExtension(configs=[('slugify', slugify)]),
        ])
        article.content = md.convert(article.content)
        article.toc = md.toc

        return article

    def get_context_data(self, **kwargs):
        context = super(PostDetailView, self).get_context_data(**kwargs)
        form = CommentForm()
        comment_list = self.object.comment_set.all()
        context.update({'form': form, 'comment_list': comment_list})
        return context


'''
def archives(request, year, month):
    article_list = Article.objects.filter(created_date__year=year,
                                       created_date__month=month
                                       ).order_by('-created_date')
    return render(request, 'blog/index.html', locals())
'''


class ArchivesView(ListView):
    model = Article
    template_name = 'blog/index.html'
    context_object_name = 'article_list'

    def get_queryset(self):
        year = self.kwargs.get('year')
        month = self.kwargs.get('month')
        return super(ArchivesView, self).get_queryset().filter(created_date__year=year,
                                                               created_date__month=month).order_by('-created_date')

'''
def category(request, pk):
    cate = get_object_or_404(Category, pk=pk)
    article_list = Article.objects.filter(category=cate).order_by('-created_date')
    return render(request, 'blog/index.html', {'article_list': article_list})
'''


class CategoryView(ListView):
    model = Article
    template_name = 'blog/index.html'
    context_object_name = 'article_list'

    def get_queryset(self):
        cate = get_object_or_404(Category, pk=self.kwargs.get('pk'))
        return super(CategoryView, self).get_queryset().filter(category=cate)


class TagView(IndexView):
    model = Article
    template_name = 'blog/index.html'
    context_object_name = 'article_list'

    def get_queryset(self):
        tag = get_object_or_404(Tag, pk=self.kwargs.get('pk'))
        return super(TagView, self).get_queryset().filter(tags=tag)


def search(request):
    q = request.GET.get('q')
    error_msg = ''

    if not q:
        error_msg = '请输入关键词'
        return render(request, 'blog/index.html', {'error_msg': error_msg})

    article_list = Article.objects.filter(Q(title__icontains=q) | Q(content__icontains=q))
    return render(request, 'blog/index.html', {'error_msg': error_msg, 'article_list': article_list})


def about(request):
    return render(request, 'blog/about.html', locals())


# def full_width(request):
#     return render(request, 'blog/full-width.html', locals())


def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = form.cleaned_data['subject']
            email = form.cleaned_data['email']
            message = form.cleaned_data['message']
            form.save()
            # send_mail(subject=subject, message=message, from_email='306084800@qq.com', recipient_list=['13262797993@163.com'], fail_silently=False)
            celery_send_email.delay(subject, message, '306084800@qq.com', ['13262797993@163.com'])
    else:
        form = ContactForm()
    return render(request, 'blog/contact.html', locals())


def signup(request):
    path = request.get_full_path()
    if request.method == 'POST':
        form = SignupForm(data=request.POST, auto_id="%s")
        if form.is_valid():
            UserModel = get_user_model()
            username = form.cleaned_data['username']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            user = UserModel.objects.create_user(username=username, email=email, password=password)
            user.save()
            auth_user = authenticate(username=username, password=password)
            auth_login(request, auth_user)
            return redirect("home")
    else:
        form = SignupForm(auto_id="%s")
    return render(request, 'blog/signup.html', locals())


def logout_view(request):
    logout(request)
    return redirect('home')


class FullView(IndexView):
    model = Article
    template_name = 'blog/full-width.html'
    context_object_name = 'article_list'
    paginate_by = 5

    def get_queryset(self):
        article_list = Article.objects.filter(is_show=True)
        for article in article_list:
            article.content = strip_tags(markdown.markdown(article.content,))[:54]
        return article_list
    #
    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     paginator = context.get('paginator')
    #     page = context.get('page_obj')
    #     is_paginated = context.get('is_paginated')
    #
    #     pagination_data = self.pagination_data(paginator, page, is_paginated)
    #     context.update(pagination_data)
    #
    #     return context
    #
    # def pagination_data(self, paginator, page, is_paginated):
    #     if not is_paginated:
    #         return {}
    #     left = []
    #     right = []
    #     left_has_more = []
    #     right_has_more = []
    #     first = False
    #     last = False
    #     page_number = page.number
    #     total_pages = paginator.num_pages
    #     page_range = paginator.page_range
    #
    #     if page_number == 1:
    #         right = page_range[page_number:page_number + 2]
    #
    #         if right[-1] < total_pages -1:
    #             right_has_more = True
    #         if right[-1] < total_pages:

blog/templates/blog/about.html
{% extends "blog/base.html" %}
{% load  staticfiles %}
{% block content %}


		<div class="content-body">
			<div class="container">
				<div class="row">
					<main class="col-md-12">
						<h1 class="page-title">关 于</h1>
						<article class="post">
							<div class="entry-content clearfix">
								<figure class="img-responsive-center">
									<img class="img-responsive" src='{% static "blog/img/me.jpg" %}' alt="Developer Image">
								</figure>
								<p>关于我：</p>
								<p>我叫徐立辰，非科班出身，初学Python及Django。根据书籍资料及网络教程，几经波折，终于搭建完成并在腾讯云上部署该博客。
									希望通过查阅Django的文档及源码，在web的开发开发上更进一步，也能把博客的功能再往外拓展开来。<br>
								</p><br>
								<p>爱好：</p>
								<p>美剧，篮球，Dota(已戒，11坑爹)  /(ㄒoㄒ)/~~</p><br>
								<p>联系方式：</p>
								<p>邮箱: 306084800@qq.com</p>
								<p>Github: https://github.com/xulichen</p>
								<div class="height-40px"></div>
								<h2 class="title text-center">Social</h2>
								<ul class="social">
									<li class="facebook"><a href="#"><span class="ion-social-facebook"></span></a></li>
									<li class="twitter"><a href="#"><span class="ion-social-twitter"></span></a></li>
									<li class="google-plus"><a href="#"><span class="ion-social-googleplus"></span></a></li>
									<li class="tumblr"><a href="#"><span class="ion-social-tumblr"></span></a></li>
								</ul>
							</div>
						</article>
					</main>
				</div>
			</div>
		</div>

		<!-- Mobile Menu -->
		<div class="overlay overlay-hugeinc">
			<button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
			<nav>
				<ul>
					<li><a href="index.html">Home</a></li>
					<li><a href="full-width.html">Blog</a></li>
					<li><a href="about.html">About</a></li>
					<li><a href="contact.html">Contact</a></li>
				</ul>
			</nav>
		</div>

		<script src="js/script.js"></script>
		
	</body>
</html>
{% endblock %}

blog/templates/blog/contact.html
{% extends "blog/base.html" %}
{% load staticfiles %}
{% block content %}

		<div class="content-body">
			<div class="container">
				<div class="row">
					<main class="col-md-12">
						<h1 class="page-title">Contact</h1>
						<article class="post">
							<div class="entry-content clearfix">
								<form action="{% url 'blog:contact' %}" method="post" class="contact-form">
									<div class="row">
										<div class="col-md-6 col-md-offset-3">
											{% csrf_token %}
											{% for field in form %}
											{{ field }}
											{% endfor %}
											<button class="btn-send btn-5 btn-5b ion-ios-paperplane"><span>Drop Me a Line</span></button>
										</div>
									</div>	<!-- row -->
								</form>
							</div>
						</article>
					</main>
				</div>
			</div>
		</div>

		<!-- Mobile Menu -->
		<div class="overlay overlay-hugeinc">
			<button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
			<nav>
				<ul>
					<li><a href="index.html">Home</a></li>
					<li><a href="full-width.html">Blog</a></li>
					<li><a href="about.html">About</a></li>
					<li><a href="contact.html">Contact</a></li>
				</ul>
			</nav>
		</div>

		<script src="js/script.js"></script>
		
	</body>
</html>
{% endblock %}

blog/templates/blog/detail.html
{% extends "blog/base.html" %}
{% load staticfiles %}
{% block content %}
{% load blog_tags %}


<article class="post post-1">
    <header class="entry-header">
        <h1 class="entry-title">{{ article.title }}</h1>
        <div class="entry-meta">
            <span class="post-category"><a href="#">{{ article.category }}</a></span>

            <span class="post-date"><a href="#"><time class="entry-date" datetime="{{ article.created_date }}">{{ article.created_date }}</time></a></span>

            <span class="post-author"><a href="#">{{ article.author }}</a></span>

            <span class="views-count"><a href="{{ article.get_absolute_url }}">{{ article.views }} 阅读</a></span>

            <span class="comments-link"><a href="#">{{ article.comment_set.count }} 评论</a></span>

        </div>
    </header>
    <div class="entry-content clearfix">
        <p>{{ article.content|safe }}</p>
    </div>
    <div class="widget-tag-cloud">
        <ul>
            标签：
            {% for tag in article.tags.all %}
                <li><a href="{% url 'blog:tag' tag.pk %}"># {{ tag.name }}</a></li>
            {% endfor %}
        </ul>
    </div>
</article>

<section class="comment-area" id="comment-area">
    <hr>
    <h3>发表评论</h3>
    <form action="{% url 'comments:article_comment' article.pk %}" method="post" class="comment-form">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-4">
                <label for="{{ form.name.id_for_label }}">名字：</label>
                {{ form.name }}
                {{ form.name.errors }}
            </div>
            <div class="col-md-4">
                <label for="{{ form.email.id_for_label }}">邮箱：</label>
                {{ form.email }}
                {{ form.email.errors }}
            </div>
            <div class="col-md-4">
                <label for="{{ form.url.id_for_label }}">URL：</label>
                {{ form.url }}
                {{ form.url.errors }}
            </div>
            <div class="col-md-12">
                <label for="{{ form.text.id_for_label }}">评论：</label>
                {{ form.text }}
                {{ form.text.errors }}
                <button type="submit" class="comment-btn">发表</button>
            </div>
        </div>    <!-- row -->
    </form>
    <div class="comment-list-panel">
        <h3>评论列表，共 <span>{{ article.comment_set.count }}</span> 条评论</h3>
        <ul class="comment-list list-unstyled">
            {% for comment in comment_list %}
                <li class="comment-item">
                    <span class="nickname">{{ comment.name }}</span>
                    <time class="submit-date"
                          datetime="{{ comment.created_date }}">{{ comment.created_date }}</time>
                    <div class="text">
                        {{ comment.text }}
                    </div>
                </li>
            {% empty %}
                暂无评论
            {% endfor %}
        </ul>
    </div>
</section>

{% endblock content %}
{% block aside %}
<div class="widget widget-content">
    <h3 class="widget-title">文章目录</h3>
    {{ article.toc|safe }}
</div>
<div class="widget widget-recent-posts">
    <h3 class="widget-title">最新文章</h3>
    {% get_recent_article as recent_article_list %}
    <ul>
        {% for recent_article in recent_article_list %}
        <li>
            <a href="{{ recent_article.get_absolute_url }}">{{ recent_article.title }}</a>
        </li>
        {% empty %}
        暂无文章
        {% endfor %}
    </ul>
    </div>
    <div class="widget widget-archives">
        <h3 class="widget-title">归档</h3>
        {% archives as date_list %}
        <ul>
            {% for date in date_list %}
            <li>
                <a href="{% url 'blog:archives' date.year date.month %}">{{ date.year}} 年 {{ date.month }} 月</a>
            </li>
            {% empty %}
            暂无归档
            {% endfor %}
        </ul>
    </div>

    <div class="widget widget-category">
        <h3 class="widget-title">分类</h3>
        {% get_categories as category_list %}
        <ul>
            {% for category in category_list %}
            <li>
                <a href="{% url 'blog:category' category.pk %}">{{ category.name }}</a>
                <span class="post-count">({{ category.num_article }})</span>
            </li>
            {% empty %}
            暂无分类
            {% endfor %}
        </ul>
    </div>
    <div class="widget widget-tag-cloud">
        <h3 class="widget-title">标签云</h3>
        {% get_tags as tag_list %}
        <ul>
            {% for tag in tag_list %}
            <li>
                <a href="{% url 'blog:tag' tag.pk %}">{{ tag.name }}</a>
            </li>
            {% empty %}
            暂无标签！
            {% endfor %}
        </ul>
    </div>
    <div class="rss">
      <a href="{% url 'rss' %}"><span class="ion-social-rss-outline"></span> RSS 订阅</a>
    </div>
{% endblock aside %}

blog/templates/blog/full-width.html
{% extends "blog/base.html" %}
{% load  staticfiles %}
{% block content %}


	<div class="content-body">
		<div class="container">
			<div class="row">
				<main class="col-md-12">
					{% for article in article_list %}
					<article class="post post-{{ blog.pk }}">
						<header class="entry-header">
							<h1 class="entry-title">
								<a href="{{ article.get_absolute_url }}"> {{ article.title }} </a>
							</h1>
							<div class="entry-meta">
								<span class="post-category"><a href="#">{{ article.category }}</a></span>

								<span class="post-date"><a href="#"><time class="entry-date" datetime="{{ article.created_date }}">{{ article.created_date }}</time></a></span>

								<span class="post-author"><a href="#">{{ article.author }}</a></span>

								<span class="views-count"><a href="{{ article.get_absolute_url }}">{{ article.views }} 阅读</a></span>

								<span class="comments-link"><a href="#">{{ article.comment_set.count }} Comments</a></span>
							</div>
						</header>
						<div class="entry-content clearfix">
							<p>{{ article.content }}</p>
							<div class="read-more cl-effect-14">
								<a href="{{ article.get_absolute_url }}" class="more-link">Continue reading <span class="meta-nav">→</span></a>
							</div>
						</div>

					</article>
					{% empty %}
					<div class="no-post">暂时还没有发布的文章！</div>
					{% endfor %}

					{% if is_paginated %}
					<div class="pagination">
					  {% if first %}
						<a href="?page=1">1</a>
					  {% endif %}
					  {% if left %}
						{% if left_has_more %}
							<span>...</span>
						{% endif %}
						{% for i in left %}
							<a href="?page={{ i }}">{{ i }}</a>
						{% endfor %}
					  {% endif %}
					  <a href="?page={{ page_obj.number }}" style="color: red">{{ page_obj.number }}</a>
					  {% if right %}
						{% for i in right %}
							<a href="?page={{ i }}">{{ i }}</a>
						{% endfor %}
						{% if right_has_more %}
							<span>...</span>
						{% endif %}
					  {% endif %}
					  {% if last %}
						<a href="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a>
					  {% endif %}
					</div>
					{% endif %}

					{% endblock content %}

					</main>
				</div>
			</div>
		</div>
		<footer id="site-footer">
			<div class="container">
				<div class="row">
					<div class="col-md-12">
						<p class="copyright">&copy; 2014 ThemeWagon.com</p>
					</div>
				</div>
			</div>
		</footer>

		<!-- Mobile Menu -->
		<div class="overlay overlay-hugeinc">
			<button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
			<nav>
				<ul>
					<li><a href="index.html">Home</a></li>
					<li><a href="full-width.html">Blog</a></li>
					<li><a href="about.html">About</a></li>
					<li><a href="contact.html">Contact</a></li>
				</ul>
			</nav>
		</div>

		<script src="js/script.js"></script>

	</body>
</html>

blog/templates/blog/index.html
{% extends "blog/base.html" %}
{% load  staticfiles %}
{% load blog_tags %}
{% block content %}

{% if error_msg %}
<p>{{ error_msg }}</p>
{% endif %}

{% for article in article_list %}
<article class="post post-{{ blog.pk }}">
    <header class="entry-header">
        <h1 class="entry-title">
            <a href="{{ article.get_absolute_url }}"> {{ article.title }} </a>
        </h1>
        <div class="entry-meta">
            <span class="post-category"><a href="#">{{ article.category }}</a></span>

            <span class="post-date"><a href="#"><time class="entry-date" datetime="{{ article.created_date }}">{{ article.created_date }}</time></a></span>

            <span class="post-author"><a href="#">{{ article.author }}</a></span>

            <span class="views-count"><a href="{{ article.get_absolute_url }}">{{ article.views }} 阅读</a></span>

            <span class="comments-link"><a href="#">{{ article.comment_set.count }} Comments</a></span>
        </div>
    </header>
    <div class="entry-content clearfix">
        <p>{{ article.excerpt }}...</p>
        <div class="read-more cl-effect-14">
            <a href="{{ article.get_absolute_url }}" class="more-link">Continue reading <span class="meta-nav">→</span></a>
        </div>
    </div>

</article>
{% empty %}
<div class="no-post">暂时还没有发布的文章！</div>
{% endfor %}

{% if is_paginated %}
<div class="pagination">
  {% if first %}
    <a href="?page=1">1</a>
  {% endif %}
  {% if left %}
    {% if left_has_more %}
        <span>...</span>
    {% endif %}
    {% for i in left %}
        <a href="?page={{ i }}">{{ i }}</a>
    {% endfor %}
  {% endif %}
  <a href="?page={{ page_obj.number }}" style="color: red">{{ page_obj.number }}</a>
  {% if right %}
    {% for i in right %}
        <a href="?page={{ i }}">{{ i }}</a>
    {% endfor %}
    {% if right_has_more %}
        <span>...</span>
    {% endif %}
  {% endif %}
  {% if last %}
    <a href="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a>
  {% endif %}
</div>
{% endif %}

{% endblock content %}

{% block aside %}
<div class="widget widget-recent-posts">
    <h3 class="widget-title">最新文章</h3>
    {% get_recent_article as recent_article_list %}
    <ul>
        {% for recent_article in recent_article_list %}
        <li>
            <a href="{{ recent_article.get_absolute_url }}">{{ recent_article.title }}</a>
        </li>
        {% empty %}
        暂无文章
        {% endfor %}
    </ul>
    </div>
    <div class="widget widget-archives">
        <h3 class="widget-title">归档</h3>
        {% archives as date_list %}
        <ul>
            {% for date in date_list %}
            <li>
                <a href="{% url 'blog:archives' date.year date.month %}">{{ date.year}} 年 {{ date.month }} 月</a>
            </li>
            {% empty %}
            暂无归档
            {% endfor %}
        </ul>
    </div>

    <div class="widget widget-category">
        <h3 class="widget-title">分类</h3>
        {% get_categories as category_list %}
        <ul>
            {% for category in category_list %}
            <li>
                <a href="{% url 'blog:category' category.pk %}">{{ category.name }}</a>
                <span class="post-count">({{ category.num_article }})</span>
            </li>
            {% empty %}
            暂无分类
            {% endfor %}
        </ul>
    </div>

    <div class="widget widget-tag-cloud">
        <h3 class="widget-title">标签云</h3>
        {% get_tags as tag_list %}
        <ul>
            {% for tag in tag_list %}
            <li>
                <a href="{% url 'blog:tag' tag.pk %}">{{ tag.name }}</a>
            </li>
            {% empty %}
            暂无标签！
            {% endfor %}
        </ul>
    </div>
    <div class="rss">
      <a href="{% url 'rss' %}"><span class="ion-social-rss-outline"></span> RSS 订阅</a>
    </div>
{% endblock aside %}